### ISSUE TITLE
써밋 웹사이트 개발 준비

### ISSUE THREAD

**Issue by soohyunpae** [creativecommonskorea/global-summit-#31]
라이언 피드백 모두 보시는 게 좋을 것 같아 공유해요- Payment
    - Please work with Matt on what we can do re: payment processing. I don't object to the idea, but don't know what's involved logistically.
- List of attendees
  - If privacy concerns and attendee consent are resolved, I'm fine with it. 
- Twitter
  - This is easy to do, though I don't think it's that important -- it's not how people read twitter (on someone else's website). I wouldn't put a lot of resources into it.
- Video streaming
  - We should plan to capture quality recordings as our primary goal, streaming is great if we have the infrastructure available. 
- Website
  - CC HQ can support some website development. There are no additional funds available for contractors. If we can't do things within the budget, we'll have to leave them out.
  - I would encourage you to keep website development to a minimum. A conference site has two primary goals: register people, and help them engage with the conference -- logistics, meeting people, and finding the program. Everything else is not that important, IMHO, and will take up resources.

기본적으로 Matt과 논의하고 우리가 필요한 내용 결정대로 진행하면 될 것 같아요. 라이언에게는 우리는 이미 일단 디자인 중이니 디자인 완성하고 공유해주겠다고 했어요. 

위에 Ryan이 얘기한대로 payment 와 privacy 이슈, 그리고 domain 관련 내용을 Matt과 논의해야할 것 같은데, 기술적인 부분이라 제가 혼자 정리하기에는 무리가 있을 것 같아요...영택님이 직접 논의하시는 게 나을까요? 아님 경희님이 앞으로 웹사이트 계속 진행하실테니까 이 단계부터 커뮤니케이션하시는 게 나을까요? 아님 제가 정리해서 모두 cc 넣고 다같이 커뮤니케이션 할까요?
참고로 Matt이 주말까지 부재중인 것 같아요. 어차피 빨라도 월요일(우리 시간 화요일)은 되어야 답이 올 것 같아요. 
## TODO
- [x] [creativecommonskorea/2015-summit](https://github.com/creativecommonskorea/2015-summit) 생성 및 범준님 추가
- [x] matt에게 dns a record 업데이트 및 ssl 인증서 공유 여부 메일로 문의
- [ ] 디지털오션 1GB 계정 구입 - 한달에 $10불 - 8, 9 ,10월 대략 3달 사용 예상?
- [ ] matt에게 dns a record ip 주소 전달하기
- [ ] ssl 보안 인증서 구매 및 서버에 설치

**Comment by mozodev** [comment]
@soohyunpae 맷은 써밋 웹사이트 계속 HQ가 호스팅할거라고 하는데, 혹시 이야기는 잘 됐나요? 좀 화가 난거 같아서 안쓰러워서 ㅎㅎ 제가 따로 메일을 보내야하나 그러고 있네요... 이게 결정이 나야 뒤에 저런 것들 구입해서 작업을 해야해서요....
